import { useState } from 'react';
import { useAuth } from '../auth/AuthContext';

export default function Auth({ onDone, initialMode='login', referralCode='' }) {
 const {login,signup}=useAuth(); const [mode,setMode]=useState(initialMode); const [form,setForm]=useState({username:'',email:'',password:'',telegramUsername:'',referralCode:referralCode||new URLSearchParams(window.location.search).get('ref')||''}); const [error,setError]=useState(null); const [busy,setBusy]=useState(false); const [telegramPopup,setTelegramPopup]=useState(false);
 const update=k=>e=>setForm({...form,[k]:e.target.value});
 const submit=async e=>{e.preventDefault();setError(null);setBusy(true);try{if(mode==='login')await login(form.email,form.password);else{await signup(form);setTelegramPopup(true);return}onDone?.()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const signupMode=mode==='signup';
 return <div className="relative min-h-screen overflow-hidden bg-[#030914] px-4 py-6 text-ink-primary"><div className="absolute -left-20 top-8 h-64 w-64 rounded-full bg-brand-blue/15 blur-3xl"/><div className="absolute -right-20 bottom-0 h-64 w-64 rounded-full bg-brand-cyan/10 blur-3xl"/>
 {telegramPopup&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-5"><div className="tt-card w-full max-w-sm rounded-3xl p-6 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-brand-blue/15 text-2xl">✈</div><h2 className="mt-4 font-display text-xl font-bold">Join Top Tier on Telegram</h2><p className="mt-2 text-xs leading-5 text-ink-muted">Join the official channel for updates and announcements.</p><a href="https://t.me/Toptiertradingchannel" target="_blank" rel="noopener noreferrer" className="mt-5 block rounded-xl bg-brand-blue py-3 text-xs font-bold text-white">Join Telegram Channel</a><button onClick={()=>{setTelegramPopup(false);onDone?.()}} className="mt-2 w-full rounded-xl border border-border py-3 text-xs">Continue</button></div></div>}
 <main className="relative mx-auto flex min-h-[calc(100vh-3rem)] max-w-md items-center justify-center"><div className="w-full">
  <div className="mb-5 text-center"><div className="mx-auto h-20 w-full max-w-xs overflow-hidden rounded-2xl border border-brand-blue/40 bg-gradient-to-br from-brand-blue/15 to-surface"><div className="flex h-full items-center justify-center text-3xl">♛</div></div><p className="mt-4 font-display text-2xl font-black">TOP <span className="text-brand-cyan">TIER</span></p><p className="text-[9px] text-ink-muted">Earn • Complete • Withdraw</p></div>
  <div className="tt-card rounded-3xl p-5"><h1 className="font-display text-xl font-bold">{signupMode?'Join Top Tier':'Welcome Back'}</h1><p className="mt-1 text-xs text-ink-muted">{signupMode?'Create your account and start earning today.':'Sign in to continue your journey and earn rewards.'}</p>
   <form onSubmit={submit} className="mt-5 space-y-2.5">{signupMode&&<input placeholder="Username" value={form.username} onChange={update('username')} required className="w-full rounded-xl border border-brand-blue/30 bg-base px-3 py-3 text-xs outline-none focus:border-brand-cyan"/>}<input type="email" placeholder="Email Address" value={form.email} onChange={update('email')} required className="w-full rounded-xl border border-brand-blue/30 bg-base px-3 py-3 text-xs outline-none focus:border-brand-cyan"/><input type="password" placeholder="Password" value={form.password} onChange={update('password')} required minLength={6} className="w-full rounded-xl border border-brand-blue/30 bg-base px-3 py-3 text-xs outline-none focus:border-brand-cyan"/>{signupMode&&<><input placeholder="Telegram Username" value={form.telegramUsername} onChange={update('telegramUsername')} className="w-full rounded-xl border border-brand-blue/30 bg-base px-3 py-3 text-xs outline-none focus:border-brand-cyan"/><input placeholder="Referral Code (optional)" value={form.referralCode} onChange={update('referralCode')} className="w-full rounded-xl border border-brand-blue/30 bg-base px-3 py-3 text-xs outline-none focus:border-brand-cyan"/></>}{error&&<p className="text-xs text-loss">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-brand-blue py-3.5 text-xs font-bold text-white">{busy?'Please wait…':signupMode?'Sign Up':'Login'}</button></form>
   <div className="my-4 flex items-center gap-3"><span className="h-px flex-1 bg-border"/><span className="text-[9px] text-ink-muted">OR</span><span className="h-px flex-1 bg-border"/></div><button type="button" className="w-full rounded-xl border border-brand-blue/30 bg-base py-3 text-xs">Continue with Google</button><button type="button" className="mt-2 w-full rounded-xl border border-brand-blue/30 bg-base py-3 text-xs">Continue with Telegram</button>
   <button onClick={()=>setMode(signupMode?'login':'signup')} className="mt-5 w-full text-[10px] text-ink-muted">{signupMode?'Already have an account? ':'Don’t have an account? '}<span className="font-bold text-brand-cyan">{signupMode?'Login':'Sign Up'}</span></button>
  </div>
 </div></main></div>;
}