import { useEffect,useState } from 'react';
import { api } from '../api/client';
import { useAuth } from '../auth/AuthContext';

export default function Profile(){
 const{logout}=useAuth();const[p,setP]=useState(null),[tg,setTg]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(null);
 useEffect(()=>{api.getMyProfile().then(d=>{setP(d);setTg(d.telegram_username||'')}).catch(e=>setError(e.message))},[]);
 const save=async e=>{e.preventDefault();setSaving(true);try{await api.updateMyProfile({telegramUsername:tg});setP(x=>({...x,telegram_username:tg}))}catch(e){setError(e.message)}finally{setSaving(false)}};
 if(error&&!p)return <p className="p-6 text-sm text-loss">{error}</p>;if(!p)return <p className="p-6 text-sm text-ink-muted">Loading…</p>;
 const initials=(p.username||'?').slice(0,2).toUpperCase();
 return <div className="mx-auto max-w-5xl px-4 pb-8 pt-5 sm:px-8"><div className="tt-card overflow-hidden rounded-3xl">
  <div className="flex items-center gap-3 border-b border-border bg-gradient-to-r from-brand-blue/20 to-surface p-5"><div className="grid h-16 w-16 place-items-center rounded-full border-2 border-brand-cyan bg-brand-blue/20 font-display text-xl font-bold">{initials}</div><div className="flex-1"><h1 className="font-display text-lg font-bold">{p.username}</h1><p className="text-[10px] text-brand-cyan">@{p.telegram_username||'telegram-not-linked'}</p><p className="text-[10px] text-ink-muted">Level {Math.max(1,Math.floor((p.total_points||0)/500)+1)} · {(p.total_points||0).toLocaleString()} pts</p></div><span>⚙</span></div>
  <div className="grid grid-cols-3 divide-x divide-border bg-surface/80"><div className="p-3 text-center"><b>{p.referral_count||0}</b><p className="text-[9px] text-ink-muted">Referrals</p></div><div className="p-3 text-center"><b>{p.tasks_completed||0}</b><p className="text-[9px] text-ink-muted">Tasks Done</p></div><div className="p-3 text-center"><b>{p.current_streak||0}</b><p className="text-[9px] text-ink-muted">Day Streak</p></div></div>
  <div className="space-y-1 p-3"><div className="rounded-xl border border-border bg-base/50 px-3 py-3 text-xs">✎ <span className="ml-2">Edit Profile</span></div><form onSubmit={save} className="rounded-xl border border-border bg-base/50 px-3 py-3"><label className="text-[10px] text-ink-muted">Telegram Username</label><div className="mt-2 flex gap-2"><input value={tg} onChange={e=>setTg(e.target.value)} placeholder="yourhandle" className="min-w-0 flex-1 rounded-lg border border-border bg-surface px-2 py-2 text-xs"/><button disabled={saving} className="rounded-lg bg-brand-blue px-3 text-[10px] font-bold text-white">{saving?'Saving…':'Save'}</button></div></form><div className="rounded-xl border border-border bg-base/50 px-3 py-3 text-xs">🔔 <span className="ml-2">Notifications</span><span className="float-right text-brand-cyan">ON</span></div><div className="rounded-xl border border-border bg-base/50 px-3 py-3 text-xs">? <span className="ml-2">Support</span></div><button onClick={logout} className="w-full rounded-xl border border-loss/30 bg-loss/5 px-3 py-3 text-left text-xs text-loss">↪ <span className="ml-2">Log Out</span></button></div>
 </div>{error&&<p className="mt-3 text-xs text-loss">{error}</p>}</div>
}