import { useEffect, useState } from 'react';
import { api } from '../api/client';

const filters=['All','Manual','Telegram','Social'];
export default function Tasks(){
 const[tasks,setTasks]=useState([]),[submissions,setSubmissions]=useState([]),[proof,setProof]=useState({}),[busy,setBusy]=useState({}),[filter,setFilter]=useState('All'),[error,setError]=useState(null);
 const load=async()=>{try{const[a,b]=await Promise.all([api.getTasks(),api.getMyTaskSubmissions()]);setTasks(a.tasks||[]);setSubmissions(b.submissions||[]);setError(null)}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);
 const submit=async(id)=>{setBusy(v=>({...v,[id]:true}));try{await api.submitTask(id,{proofFile:proof[id]?.file});setProof(v=>({...v,[id]:undefined}));await load()}catch(e){setError(e.message)}finally{setBusy(v=>({...v,[id]:false}))}};
 const telegram=async(id)=>{setBusy(v=>({...v,[id]:true}));try{const r=await api.startTelegramTask(id);if(r.telegram_url)window.open(r.telegram_url,'_blank','noopener,noreferrer');await load()}catch(e){setError(e.message)}finally{setBusy(v=>({...v,[id]:false}))}};
 const byTask=Object.fromEntries(submissions.map(s=>[s.task_id,s]));
 const visible=tasks.filter(t=>filter==='All'||filter==='Social'||(filter==='Telegram'?t.task_type==='telegram':t.task_type!=='telegram'));
 return <div className="mx-auto max-w-5xl px-4 pb-8 pt-5 sm:px-8">
  <div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold">Tasks</h1><p className="text-xs text-ink-muted">Complete tasks to earn points</p></div><button className="grid h-10 w-10 place-items-center rounded-full border border-border bg-surface text-xl text-ink-primary">+</button></div>
  <div className="mt-4 grid grid-cols-4 gap-1 rounded-2xl bg-surface p-1">{filters.map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-xl px-2 py-2 text-[10px] font-bold ${filter===x?'bg-brand-blue text-white shadow-[0_0_18px_rgba(0,140,255,.25)]':'text-ink-muted'}`}>{x}</button>)}</div>
  {error&&<div className="mt-3 rounded-xl border border-loss/30 bg-loss/5 p-3 text-xs text-loss">{error}</div>}
  <div className="mt-4 space-y-3">{visible.map(task=>{const s=byTask[task.id],file=proof[task.id]?.file,isTelegram=task.task_type==='telegram';return <article key={task.id} className="tt-card rounded-2xl p-3">
   <div className="flex gap-3"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl border text-xl ${isTelegram?'border-[#229ED9]/50 bg-[#229ED9]/10':'border-brand-blue/40 bg-brand-blue/10'}`}>{isTelegram?'✈':'▣'}</div><div className="min-w-0 flex-1">
    <div className="flex items-start justify-between gap-2"><div><h2 className="text-sm font-bold">{task.title}</h2><p className="mt-1 text-[10px] leading-4 text-ink-muted">{task.description||'Complete this task and earn points.'}</p></div><span className="rounded-full bg-brand-blue/15 px-2 py-1 text-[9px] font-bold text-brand-cyan">+{task.points} pts</span></div>
    {!s?isTelegram?<button disabled={busy[task.id]} onClick={()=>telegram(task.id)} className="mt-3 w-full rounded-xl bg-brand-blue py-3 text-[10px] font-bold text-white">{busy[task.id]?'Opening Telegram…':'Open Telegram Bot'}</button>:<div className="mt-3"><label className="flex items-center justify-between rounded-xl border border-dashed border-brand-blue/60 bg-brand-blue/5 p-3"><span><b className="block text-[10px]">{file?.name||'Share a screenshot'}</b><small className="text-[9px] text-ink-muted">PNG, JPG or WEBP</small></span><span className="rounded-lg bg-brand-blue px-3 py-2 text-[9px] font-bold text-white">Upload Screenshot</span><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setProof(v=>({...v,[task.id]:{file:e.target.files?.[0]||null}}))}/></label><button disabled={!file||busy[task.id]} onClick={()=>submit(task.id)} className="mt-2 w-full rounded-xl bg-brand-blue py-3 text-[10px] font-bold text-white disabled:opacity-40">{busy[task.id]?'Submitting…':'Submit'}</button></div>:<div className="mt-3 rounded-xl border border-border bg-base/50 p-3 text-[10px]"><span className="text-ink-muted">Submission status</span><b className="float-right capitalize text-brand-cyan">{s.status}</b></div>}
    {task.link&&<a href={task.link} target="_blank" rel="noreferrer" className="mt-2 block text-center text-[9px] text-brand-cyan">View instructions ↗</a>}
   </div></div></article>})}{!visible.length&&<div className="tt-card rounded-2xl p-8 text-center text-xs text-ink-muted">No active tasks in this category.</div>}</div>
 </div>
}